language: node_js
node_js:
- node
notifications: 
email: false
deploy:
  provider: heroku
  api_key:
    secure: CFlP3GdiuPOvKsO37a8HBB0JJVenL/FKO0HG1Kgkq/ArEeme7XLHhZuO9ATv+g8hwPHfCeOo2UPCt4zv5o2DhcuhDuI2ClvJc6PTKRvO3Vf5vMQsz51/JPUV9sns7+98LkYXOfX/TTm8rGAtBvvRvJ+Ef0v04hNLTJ2STnOsFhtaxY+2CGaoDXzjr2w6jkUMzFC9ofTKvVcoueg8Uu2Gv4nwEwvZ+DNPvlbXzfFWwg08dJsnbJQs/I0+RZp8V/m8s/WwxKfiZ7Do34iLv5SR9P30KnOaVr90Q7UFcutmKXhyFK9EfcatQb7h4i2nj0o5lbmygCN+3cepWOeyyijizjaaFU3OmZatVhF2kbPNDeiplrHmhzwNgvm8my20GJxT5N9rIFi9QpGa1QLLXMkLeKgCMTOSDMT9ViPQY1KK5JV7ypxWVNKXWsqvD2um7Ys+PG+hepRS/dlbpyFAAqp8H3vPAfCCgkAR46KUvCvLC+dLgSGrQIZP0yKy0aze/yzU36BmYM1aE4pSBXydT72fD73xMDrxlydZeEfsz2Iy6g2NxreceqkjcroShhO1eztYr/wP0CIlbLzSsjTQJguyQkSAPtjEWyecvilRmN8C8zSW+0uAQZkkYnvZMpvt6YNZWfsI2DQWppXCeedKQJyt1YZlNYshqrOmSPQ8Xsy3iMA=
  app: rocky-eyrie-76288
  skip_cleanup: true
