language: node_js
node_js:
- node
notifications: 
email: false
deploy:
  provider: heroku
  api_key:
    secure: KYCKZKvkZ/ydHGaPFk1Xlls5Pq31jElpFusKnUEJjmMYrcJxFz/ljvlYkfN5YUtV5H7xcuWqxrvC5RT2s2ejwzyEZRbNovNlX3P9m15B3FakJeOcVdCQ6tzJpbpfDIIOXJaSXFdbov3FCLm5lIhsLBVrjlyITa/sQW6PbEQq3i+wgFxQpW6jL3slROVUjqm9sz0T9kZihAPhSymt3iJwMpZQQjAYQWyNCrp32ohDCcG0lOnoQwdFA8cJ2UVSDrLWuTST2qhoS7yuEB/czKGdyysDBGPrI5lhvdkdIkiGQne1DDqLRnkwGgue2dLhAcNXwlHVPfPOclKoldN8U7uluADm2ou9QlRz/vZsoNnZM9JBFMNkMJW0w7DU4DEqimslc0+rhvnktvZjxji4lzp1OUGZ41EVoKxiXD/fRpMWHhdOgVmNH6tMb4EKB02RtCBpTU6g8VXRrPq6uZ5lEfl+KWsLPOEyAlC3fRGi/t/+WF5SW1H1nlYcWSOfePgkwe2KIlZVdrWHTHngdMfAnc3sSZW05tMjuXCFUQFrSvrJHjs9RZc3M4wvK2Cn5b5u8djMArwmEehRx9jhX37u9+7xiBZFN4W9CSwBgGqf5GAKpyZczDe42zd4nhUPY7Rl+ETOqmvNa7u4F0KKZY5sMnQf/JPQPdID9dQduU+PrXljjD8=
  app: rocky-eyrie-76288
  skip_cleanup: true
